# Docker image of source for OpenJDK
# VERSION 0.0.2
# Author: bolingcavalry

#基础镜像使用bash:5.0-rc，特点是体积小
FROM bash:5.0-rc

#作者
MAINTAINER BolingCavalry <zq2599@gmail.com>

#定义源码存放目录
ENV SRC_PATH /src

#定义OpenJDK源码文件夹名称
ENV OPENJDK_SRC_PACKAGE_NAME jdk11

#创建目录
RUN mkdir $SRC_PATH

#把分割过的源码复制到工作目录，这么写可以保证每个文件layer都不大，这样下载镜像时如果中途失败，就不用重新下载一个巨大的layer
COPY ./$OPENJDK_SRC_PACKAGE_NAME-af $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-an $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-av $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bd $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bl $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bt $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cb $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cj $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cr $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cz $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dh $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dp $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dx $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ef $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ag $SRC_PATH/ 
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ao $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-aw $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-be $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bm $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bu $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cc $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ck $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cs $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-da $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-di $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dq $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dy $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-eg $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ah $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ap $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ax $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bf $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bn $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bv $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cd $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cl $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ct $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-db $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dj $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dr $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dz $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-eh $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-aa $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ai $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-aq $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ay $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bg $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bo $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bw $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ce $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cm $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cu $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dc $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dk $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ds $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ea $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ei $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ab $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-aj $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ar $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-az $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bh $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bp $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bx $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cf $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cn $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cv $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dd $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dl $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dt $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-eb $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ej $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ac $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ak $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-as $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ba $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bi $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bq $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-by $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cg $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-co $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cw $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-de $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dm $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-du $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ec $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ek $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ad $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-al $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-at $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bb $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bj $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-br $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bz $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ch $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cp $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cx $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-df $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dn $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dv $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ed $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-el $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ae $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-am $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-au $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bc $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bk $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-bs $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ca $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ci $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cq $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-cy $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dg $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-do $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-dw $SRC_PATH/
COPY ./$OPENJDK_SRC_PACKAGE_NAME-ee $SRC_PATH/

#命令行文件复制到工作目录
COPY ./cmd.sh /

RUN chmod a+x /cmd.sh

CMD ["bash", "/cmd.sh"]
